### ISSUE TITLE
Example showcase: loading bar gets stuck on meta file

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#1119]
Testing with Chrome 122.0.6261.129, Firefox 123.0.1 on macOS 14.2.1.

This seems to occasionally affect examples that load assets. I haven't been able to totally nail down the conditions that result in this behavior.

<img width="1201" alt="image" src="https://github.com/bevyengine/bevy-website/assets/200550/9439c8e2-5413-43df-838e-7e4dfe4f3674">

The issue seems to resolve itself after refreshing the page, but clearing the browser cache or restarting the browser don't seem to reintroduce the issue.

**Comment by mockersf** [comment]
Should be fixed by #840, but I think you have to clean the cache of all examples you already loaded

**Comment by TrialDragon** [comment]
> Should be fixed by #840, but I think you have to clean the cache of all examples you already loaded

Fresh cache (deleted bevyengine.org site data from firefox) and I don't think I used the site, or at least this example, before that was even merged.

![image](https://github.com/bevyengine/bevy-website/assets/31419708/f2900057-0d5a-4de4-82b8-40f2dcfabb1e)

I don't think this was fixed.

**Comment by rparrett** [comment]
Is it possible that we need to purge the cloudflare cache or something?

**Comment by TrialDragon** [comment]
Hmm, correction on my earlier statement; it wasn't cleaning the cache, it was refreshing the page (that happens alongside `Ctrl + F5`) like you already mentioned that solved it. But this doesn't happen on fresh browser install, so it is fixed for anyone who has never visited the site before. I wonder if you need to do a full nuke and delete entire browser history, cache, et cetera to fix this on a site that did visit.

**Comment by rparrett** [comment]
3 weeks later, I still occasionally see this on the same `sprite` example.

> I wonder if you need to do a full nuke and delete entire browser history, cache, et cetera to fix this on a browser that did visit.

If that is the case, and there's some workaround we can do on our end, we probably should.

But it feels like there might be something intermittent or racey going on here.
