### ISSUE TITLE
Bevy Example panicked

### ISSUE THREAD

**Issue by lomirus** [bevyengine/bevy-website#1123]
This [page](https://bevyengine.org/examples/2D%20Rendering/mesh2d-manual/) panicked on Chrome 123.0.6312.59.

![QQ截图20240321000340](https://github.com/bevyengine/bevy-website/assets/21173956/30a753be-370f-492d-baa1-a63fea206d05)

**Comment by rparrett** [comment]
The underlying bug was fixed by https://github.com/bevyengine/bevy/pull/10812 and released in Bevy 0.13.1, but there is an issue with the deployment of examples build with 0.13.1 to the website that is being worked on.

**Comment by mockersf** [comment]
this will be fixed by rebuilding the examples after https://github.com/bevyengine/bevy-website/pull/1124 has been merged

**Comment by BD103** [comment]
Keep an eye on https://github.com/bevyengine/bevy-website/actions/runs/8426552947, which should finish in about 2 hours and fix the problem.

**Comment by lomirus** [comment]
This problem still exists:
![image](https://github.com/bevyengine/bevy-website/assets/21173956/4bc0773c-fb90-41fc-ab81-f20a3777e47a)

**Comment by BD103** [comment]
Could you please try clearing your browser cache and refreshing the page?

**Comment by lomirus** [comment]
I have enabled the "Disable cache" option in the Network tab and tried the "Reload Cache and Hard Reload", but it still reproduced.

The returned `wasm_example_bg.wasm` seems the lastest.

![image](https://github.com/bevyengine/bevy-website/assets/21173956/a46dd0da-c05e-4067-8489-93b7e084a62a)

**Comment by rparrett** [comment]
It looks like the other examples with custom shaders are now working after the deployment, but "mesh2d manual" specifically is still broken. This could be a separate issue that was not fixed in 0.13.1.

https://bevyengine.org/examples/2D%20Rendering/mesh2d-manual/

**Comment by mockersf** [comment]
that example was broken for another additional reason than the other ones, should be fixed by https://github.com/bevyengine/bevy/pull/12753

**Comment by mockersf** [comment]
fixed now with the 0.13.2 release
